### ISSUE TITLE
Tag support for expiration

### ISSUE THREAD

**Issue by se** [TitaniumSoft/yakari#11]
Expiration tags support would be great for expire cache item / group with common tag or tags.

For example.

```csharp
Yakari.Cache.Expire("City");
```

or

```csharp
Yakari.Cache.Expire("Country", "City", "State", "Street");
```

A cache item or group can be include more than one tag.

**Comment by efaruk** [comment]
We will going to add region/group support for both memory management and object sharing. Also we already have

`ILocalCacheProvider.Delete("City")  //Also it will be distributed to all instances...`

When we implement region/group we will support region/group cache invalidation.

But i have to say, tagging instead of grouping could be more interesting. Let me think about it for a while and I'm going to close this issue and add a new one #12
